# Form implementation generated from reading ui file 'ui/ui.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 687)
        MainWindow.setStyleSheet("background-color: #22222e")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 480, 270))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.frame.setFont(font)
        self.frame.setStyleSheet("background-color: #fb5b5d")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setGeometry(QtCore.QRect(80, 50, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Showcard Gothic")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.label.setStyleSheet("color: white;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setEnabled(True)
        self.label_2.setGeometry(QtCore.QRect(320, 40, 80, 80))
        self.label_2.setMouseTracking(False)
        self.label_2.setStyleSheet("")
        self.label_2.setLineWidth(0)
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("ui\\../Pictures/change.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.inputAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.inputAmount.setGeometry(QtCore.QRect(50, 360, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.inputAmount.setFont(font)
        self.inputAmount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white;")
        self.inputAmount.setText("")
        self.inputAmount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inputAmount.setObjectName("inputAmount")
        self.outputAmount = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.outputAmount.setGeometry(QtCore.QRect(50, 520, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.outputAmount.setFont(font)
        self.outputAmount.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white;")
        self.outputAmount.setText("")
        self.outputAmount.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.outputAmount.setObjectName("outputAmount")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(50, 610, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton {\n"
"    background-color: #fb5b5d;\n"
"    border-radius: 30px;\n"
"    color: white;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"     background-color: #fa4244;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.inputCurrency = QtWidgets.QComboBox(parent=self.centralwidget)
        self.inputCurrency.setGeometry(QtCore.QRect(50, 280, 380, 60))
        self.inputCurrency.setAutoFillBackground(False)
        self.inputCurrency.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white;")
        self.inputCurrency.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.inputCurrency.setDuplicatesEnabled(False)
        self.inputCurrency.setObjectName("inputCurrency")
        self.outputCurrency = QtWidgets.QComboBox(parent=self.centralwidget)
        self.outputCurrency.setGeometry(QtCore.QRect(50, 440, 380, 60))
        self.outputCurrency.setAutoFillBackground(False)
        self.outputCurrency.setStyleSheet("background-color: #22222e;\n"
"border: 2px solid #f66867;\n"
"border-radius: 30px;\n"
"color: white;")
        self.outputCurrency.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAtBottom)
        self.outputCurrency.setDuplicatesEnabled(False)
        self.outputCurrency.setObjectName("outputCurrency")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.inputCurrency.setCurrentIndex(-1)
        self.outputCurrency.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MoneyChanger"))
        self.inputAmount.setToolTip(_translate("MainWindow", "<html><head/><body><p>sd</p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "CONVERT"))
